# Railway Nixpacks configuration for Spring Boot
providers = ["java"]

[phases.build]
cmds = [
  "mvn clean package -DskipTests",
  "cp target/florist-backend-1.0.0.jar app.jar"
]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar app.jar"

[variables]
MAVEN_OPTS = "-Xmx1024m"
JAVA_TOOL_OPTIONS = "-Xmx1024m -XX:MaxMetaspaceSize=256m"
