# Force Railway to use Java/Maven build (NOT Docker)
providers = ["java"]

[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.build]
cmds = [
  "mvn clean package -DskipTests -q",
  "cp target/florist-backend-1.0.0.jar app.jar"
]

[phases.start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=railway -jar app.jar"

[variables]
MAVEN_OPTS = "-Xmx512m -XX:MaxMetaspaceSize=128m"
JAVA_TOOL_OPTIONS = "-Xmx512m -XX:MaxMetaspaceSize=128m"
